### ISSUE TITLE
Комментарии по схеме

### ISSUE THREAD

**Issue by kharvd** [anthonycherepkov/db-project#1]
1. phone_number (integer) -- украинские номера содержат 12 символов. Это не влезет в Integer. Лучше varchar(30).
2. password (integer) -- если это хеш, то Integer точно не подходит http://stackoverflow.com/questions/1054022/best-way-to-store-password-in-database
3. Составной ключ для classes лучше заменить на суррогатный.
4. В таблицу оценок тоже можно добавить суррогатный ключ

**Comment by Anton-Cherepkov** [comment]
1. Теперь number имеет тип varchar(30)
2. Теперь password имеет тип varchar(32). В нём будет храниться md5-хэш.
3. Для classes добавлен суррогатный ключ class_id.
4. Для marks добавлен суррогатный ключ mark_id.
